"use client";
import {useEffect,useMemo,useState} from "react";
import type {ErpScope} from "@/lib/erpScope";
import {useAuthStore} from "@/store/useAuthStore";
interface Props{activeItem:string;scope:ErpScope;permissions:readonly string[]}
type Row={id:string;name:string;cariType?:"SUPPLIER"|"TAILOR"|"INSTALLER"|null};
const cls="min-h-10 rounded-lg border border-slate-300 bg-white px-3 text-sm dark:border-slate-700 dark:bg-slate-950";
export function PayableInstrumentWorkspace({activeItem,scope,permissions}:Props){
 const token=useAuthStore(s=>s.sessionToken);const type=activeItem==="Çek ile Ödeme"?"CHEQUE":activeItem==="Senet ile Ödeme"?"NOTE":null;
 const allowed=Boolean(type&&permissions.includes(type==="CHEQUE"?"finance.cheque.issue.create":"finance.note.issue.create"));
 const [rows,setRows]=useState<Row[]>([]),[cp,setCp]=useState(""),[amount,setAmount]=useState(""),[no,setNo]=useState(""),[drawer,setDrawer]=useState(""),[bank,setBank]=useState(""),[due,setDue]=useState(""),[desc,setDesc]=useState(""),[msg,setMsg]=useState("");
 const [iid,setIid]=useState(""),[to,setTo]=useState<"PAID"|"RETURNED"|"CANCELLED">("PAID"),[bankId,setBankId]=useState(""),[reason,setReason]=useState("");
 useEffect(()=>{if(!allowed||!token)return;void fetch("/api/finance/accounts",{headers:{Authorization:`Bearer ${token}`},cache:"no-store"}).then(r=>r.json()).then(b=>setRows(Array.isArray(b?.counterparties)?b.counterparties:[])).catch(()=>setMsg("Cari listesi alınamadı."))},[allowed,token]);
 const selected=useMemo(()=>rows.find(x=>x.id===cp)||null,[rows,cp]);if(!type||!allowed)return null;
 async function issue(){const n=Number(amount.replace(",","."));if(!token||!selected||!Number.isFinite(n)||n<=0||!no.trim()||!drawer.trim()||!due||(type==="CHEQUE"&&!bank.trim())){setMsg("Zorunlu alanları kontrol edin.");return}const op=crypto.randomUUID();const body={payableInstrumentCommand:{...scope,operationId:op,idempotencyKey:`PAYABLE_INSTRUMENT:${op}`,instrumentType:type,counterpartyId:selected.id,counterpartyType:selected.cariType||"SUPPLIER",amount:n,currency:"TRY",occurredAt:new Date().toISOString(),description:desc.trim()||null,instrument:{instrumentNumber:no.trim(),drawerName:drawer.trim(),bankName:bank.trim()||null,dueDate:due}}};const r=await fetch("/api/finance/operations",{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify(body)});const b=await r.json().catch(()=>null);setMsg(r.ok?`Evrak oluşturuldu: ${b?.instrument_id||""}`:(b?.error||b?.reason||"İşlem başarısız."))}
 async function transition(){if(!token||!iid.trim())return;const op=crypto.randomUUID();const body={payableInstrumentTransitionCommand:{...scope,operationId:op,idempotencyKey:`PAYABLE_INSTRUMENT_TRANSITION:${op}`,instrumentId:iid.trim(),instrumentType:type,fromState:"ISSUED",toState:to,bankAccountId:to==="PAID"?bankId.trim()||null:null,reason:to==="PAID"?null:reason.trim()||null,occurredAt:new Date().toISOString()}};const r=await fetch("/api/finance/operations",{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify(body)});const b=await r.json().catch(()=>null);setMsg(r.ok?"Evrak durumu güncellendi.":(b?.error||b?.reason||"İşlem başarısız."))}
 return <div className="mt-4 grid gap-4"><div className="grid gap-3 rounded-xl border p-4"><strong>{type==="CHEQUE"?"Çek":"Senet"} ile ödeme</strong><select className={cls} value={cp} onChange={e=>setCp(e.target.value)}><option value="">Cari seçin</option>{rows.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input className={cls} placeholder="Tutar" value={amount} onChange={e=>setAmount(e.target.value)}/><input className={cls} placeholder="Evrak numarası" value={no} onChange={e=>setNo(e.target.value)}/><input className={cls} placeholder="Keşideci / düzenleyen" value={drawer} onChange={e=>setDrawer(e.target.value)}/>{type==="CHEQUE"?<input className={cls} placeholder="Banka" value={bank} onChange={e=>setBank(e.target.value)}/>:null}<input type="date" className={cls} value={due} onChange={e=>setDue(e.target.value)}/><input className={cls} placeholder="Açıklama" value={desc} onChange={e=>setDesc(e.target.value)}/><button type="button" onClick={()=>void issue()} className="min-h-10 rounded-lg bg-blue-600 px-4 text-sm font-bold text-white">Evrakı düzenle ve ödemeyi kaydet</button></div><div className="grid gap-3 rounded-xl border p-4"><strong>Evrak yaşam döngüsü</strong><input className={cls} placeholder="Instrument UUID" value={iid} onChange={e=>setIid(e.target.value)}/><select className={cls} value={to} onChange={e=>setTo(e.target.value as typeof to)}><option value="PAID">Ödendi</option><option value="RETURNED">İade</option><option value="CANCELLED">İptal</option></select>{to==="PAID"?<input className={cls} placeholder="Banka hesap UUID" value={bankId} onChange={e=>setBankId(e.target.value)}/>:<input className={cls} placeholder="Gerekçe" value={reason} onChange={e=>setReason(e.target.value)}/>}<button type="button" onClick={()=>void transition()} className="min-h-10 rounded-lg border px-4 text-sm font-bold">Durumu uygula</button></div>{msg?<p className="text-sm">{msg}</p>:null}</div>
}